[CONFIG]
#resnet16 resnet34 resnet50 resnet152 or simple_convnet
model= 				resnet34
sceduler=			"fit_one_cycle" # can be "fit_one_cycle" or "fixed" - if fit one cycle the learning rate is adjusted/lowered with the GradienClip function 

loss_function=			"focal" # can be "cross_entropy" or "focal"# the metric to use for loss, use either "focal", "dice" or "combined" 
dev_mode=			false # if true, only 10 images will be used for training for debug mode 

#typically 100
epochs=				10
ignore_index=			0 #what label should be ignored when computing the loss - so currently will the "unkown" be ignored when computing the loss 



#if resuming a training that was saved during epoch X. Set last_epoch to X. and model_to_load=  to the saved model
#last epoch will make the sceduler move to the correct place
#model_to_load will initialize the weights correctly
last_epoch= false 
model_to_load = false
 

# Save the model af iteration modulus save_on_batch_iter_modulus_n (only value >= 2 does something) typical use >1000
save_on_batch_iter_modulus_n = 10000

freeze=				false # freese the decoder if set to true


#for each datatype, list what channels to use, the channels, means and stas should match in length.
datatypes = ["rgb","cir","OrtoRGB","OrtoCIR","DSM","DTM"]
channels= 			[[0,1,2],[0],[0,1,2],[0],[0],[0]]
means = 			[0.485, 0.456, 0.406,0.40779021,0.485, 0.456, 0.406,0.40779021,0.5,0.5]
stds = 				[0.229, 0.224, 0.225,0.15176421,0.229, 0.224, 0.225,0.15176421,1.0,1.0]

to_fp16 = false ## using 16 or 32 bit floating points, be aware for some of the models it can cause it to become unstable

#typically 8 (to small values casues the batch normalization to produce nan values)
batch_size = 8
pin_memory = false
prefetch_factor = 2 # how many batches to prepare in advance for each worker, default is 2. Setting it to 0 will disable prefetching. Setting it to a higher value can speed up data loading, but it also increases memory usage.
n_acc = 1 # number of batches to accumulate gradients over before performing an optimizer step. This is useful for simulating a larger effective batch size when GPU memory is limited.
#typically 4 but on windows it must be set to 0. 
num_workers = 4
lr =  0.002 # the highest the learning rate gets to for the fit one cycle or just the start rate for fixed 
gradient_clip = 0.02 # To prevent exploding gradients, we can set a maximum value for the gradients during training. If the gradients exceed this value, they will be scaled down to the specified threshold.
im_type= ".tif"
label_image_type= ".tif"

transforms =["Transpose","ShiftScaleRotate","RandomShadow","GaussNoise","RandomBrightness","channel_dropout"] # 
# channel_dropout needs to know what channels that are allowed to be dropped
droppable_channels = [0,1,2,3,4,5,6,7,8,9] # list of channels that can be dropped when using the channel_dropout augmentation
 
			
#should a missklassification of some labels be weighted differently?
class_weights =			false #if used combined loss the cross entropy will take class inbalance into account 


[DATASET]
path_to_images =		../multi_channel_dataset_creation/example_dataset/data/splitted/rgb # path to images used, should be a end folder but will take all the folders in splitted
path_to_labels = 		../multi_channel_dataset_creation/example_dataset/labels/splitted_labels
path_to_dataset= 		../multi_channel_dataset_creation/example_dataset/
path_to_all_txt=		../multi_channel_dataset_creation/example_dataset/data/all.txt
path_to_valid_txt=		../multi_channel_dataset_creation/example_dataset/data/valid.txt
path_to_codes=			../multi_channel_dataset_creation/example_dataset/labels/codes.txt
experiment_root=		../logs_and_models/example_dataset_iter_1
[NAME]
job_name=			"iter_1" # name of the job running **NB** should be changed evertime a new job is run else it rewrite on old runs with the same name 


[loading_extra_labels_froim_building_masks]
extra_labels = "None" 
